### PR TITLE
include more info in downloads/exports and support all-student download

### LINKED ISSUE #112: Download all students' data at once
**Problem**: It is kinda annoying to get all student's data
**Solution**:  Make it easier to download all student's data 
**Description**: Currently, in order to download a student's data, you have to go to their dashboard page directly and click on the icon next to their name (bug exists, that will be fixed soon). That means to download all students' data, you have to click on every student's data (and correctly avoid test accounts). Tedious af, so let's have a single point of contact where a researcher can download ALL their students' data at once. To see the researchers' side of things, you can use my researcher account:

login: connietliu2020@gmail.com
password: password (pls don't try to change it no this is not part of the password)

**Specs**:
- [ ] Add some sort of feature (button/icon) to download all students' data at once
    - [ ] can be a download icon next to the word "students" when you first log into a researcher account (see potential design below)
- [ ] avoid our test accounts (only get real students' data)
- [ ] get all the data for each actual student
    - [ ] data should be in accordance with #115 for each student
- [ ] Some sort of organization so that we can tell what data belongs to which student in the downloaded file

**Resources**: [Cindy ily](https://www.notion.so/sandboxnu/Vocab-Buddy-Reported-Bugs-17922cac823041c189795da750e2b2fe) (SEE POINT 6)

download_all_vocab_buddy

### LINKED ISSUE #115: Download correct data according to researchers' specs
**Problem:** The current downloaded data doesn't match what the researchers want
**Solution:** we need to make it so that we have more specific data when it gets downloaded
**Description:** Researchers want more specific data than what we currently have. See attached files for what currently gets downloaded compared to what they want (it comes in a zipped folder with a folder of the below files...I just took the files out of the zipped folder). Potentially might also have to change how data is stored in firebase + the data we send them

**Specs**:
- [ ] Initial Assessment data 
     - [ ] student's picture response (A, B, C, or D?)
     - [ ] correct or incorrect
     - [ ] items completed before reaching 24 words
     - [ ] time taken (if possible)?
- [ ] Interventions
     - [ ] student's item selected 
     - [ ] correct or incorrect
     - [ ] time taken to do assessment
- [ ] Session follow up assessments
     - [ ] student's picture response (A, B, C, or D?)
     - [ ] correct or incorrect
     - [ ] time taken to do assessment
     
See [Number 4 here](https://www.notion.so/sandboxnu/Vocab-Buddy-Reported-Bugs-17922cac823041c189795da750e2b2fe) for more thorough explanation of data wanted 

See files for data that does currently get downloaded (of the Constance account)
[pre-assessment.csv](https://github.com/sandboxnu/vocab-buddy/files/9390696/pre-assessment.csv)
[session1.csv](https://github.com/sandboxnu/vocab-buddy/files/9390697/session1.csv)
[session2.csv](https://github.com/sandboxnu/vocab-buddy/files/9390698/session2.csv)
[session3.csv](https://github.com/sandboxnu/vocab-buddy/files/9390699/session3.csv)
[session4.csv](https://github.com/sandboxnu/vocab-buddy/files/9390700/session4.csv)
[session5.csv](https://github.com/sandboxnu/vocab-buddy/files/9390701/session5.csv)
[session6.csv](https://github.com/sandboxnu/vocab-buddy/files/9390704/session6.csv)
[session7.csv](https://github.com/sandboxnu/vocab-buddy/files/9390705/session7.csv)
[session8.csv](https://github.com/sandboxnu/vocab-buddy/files/9390706/session8.csv)

### PR DESCRIPTION
**Pull request by dillydally414**
Closes #112 
Closes #115

### CODE REVIEW

File: frontend/src/firebase/firebaseInteractor.ts [hunk 1]
```diff
@@ -586,41 +606,99 @@ export default class FirebaseInteractor {
...
+      throw new Error("Error downloading data. Please try again.");
+    }
+    const students = await this.getAllStudents();
+    const promises = students.map((student) =>
+      this.getDataForOneUser(student.id, student.name, folder).catch((error) =>
+        console.log(error)
+      )
+    );
+    await Promise.all(promises);
+    let fileBlob = await zip.generateAsync({ type: "blob" });
```
Comment (clue4) [inline frontend/src/firebase/firebaseInteractor.ts:619]: why is it called a blob lol (not an important question)

File: frontend/src/firebase/firebaseInteractor.ts [hunk 2]
```diff
@@ -170,7 +174,7 @@ export default class FirebaseInteractor {
     let wordIds = words.docs.map((word) => word.id);
     let newAssessmentFields = {
       currentIndex: 0,
-      durationInSeconds: 0,
+      durationsInSeconds: 0,
```
Comment (clue4) [inline frontend/src/firebase/firebaseInteractor.ts:179]: was this named incorrectly or did you just end up changing the field name to be more accurate?

File: uploadscript/reset-database.js [hunk 3]
```diff
@@ -0,0 +1,55 @@
+if (process.argv[2].match(/y(es)?/i)) {
```
Comment (clue4) [inline uploadscript/reset-database.js]: ooh nice writing up this script so we don't have to do manual deletion haha

worth changing the name of the uploadscript package to be more general since it's no longer just for the uploading script? and worth renmaing the script.js file to be upload-script.js?

File: frontend/src/firebase/firebaseInteractor.ts [hunk 4]
```diff
@@ -515,7 +531,8 @@ export default class FirebaseInteractor {
       | undefined = undefined;
 
     if (assessmentForSession !== undefined) {
-      assessmentDuration = assessmentForSession.data().durationInSeconds;
+      assessmentDuration =
+        Math.round(assessmentForSession.data().durationsInSeconds * 100) / 100;
```
Comment (clue4) [inline frontend/src/firebase/firebaseInteractor.ts:531]: what's this change for / is the durationInSeconds not giving back a clean number or something?

**Review by clue4 — COMMENTED** [review]
haven't yet tested this, once I do and see that everything works will update this to approved (just to be a good developer otherwise i'd have approved this LOL)

code makes sense to me, had a few questions / thoughts

File: frontend/src/firebase/firebaseInteractor.ts (hunk 1 above)
Comment (dillydally414) [reply frontend/src/firebase/firebaseInteractor.ts:619]: https://developer.mozilla.org/en-US/docs/Web/API/Blob

File: frontend/src/firebase/firebaseInteractor.ts (hunk 2 above)
Comment (dillydally414) [reply frontend/src/firebase/firebaseInteractor.ts:179]: in some places it was named durationInSeconds and some it was named durationsInSeconds, and some database entries actually had both, but durationInSeconds was always 0 so I just decided to use the durationsInSeconds even though grammatically speaking it makes me annoyed

File: uploadscript/reset-database.js (hunk 3 above)
Comment (dillydally414) [reply uploadscript/reset-database.js]: yar

File: frontend/src/firebase/firebaseInteractor.ts (hunk 4 above)
Comment (dillydally414) [reply frontend/src/firebase/firebaseInteractor.ts:531]: it's a float so this is just rounding to 2 decimal places so they don't get data that looks like 1254.12000000001 seconds

**Comment by dillydally414** [comment]
FYI: for whatever reason our API key was just hangin out in the upload script, so I regenerated it and moved it to a gitignore file cause.. that just doesn't seem like something we wanna have hanging out :D

**Comment by dillydally414** [comment]
@clue4 to test the additional data in the UI/downloads check out the `dillons` user since it's the only one that actually has that data tracked :skull: otherwise there will be a bunch of undefineds in your csvs. Though you should try the download all button too ig

File: frontend/src/firebase/firebaseInteractor.ts [hunk 5]
```diff
@@ -142,9 +142,13 @@ export default class FirebaseInteractor {
     let idToUse = id || this.auth.currentUser?.uid;
     let user = await this.db.collection("users").doc(idToUse).get();
     let userData = user.data();
-    if (idToUse != null && userData != null) {
-      return this.getUserFromData(idToUse, userData);
+    if (userData != undefined) {
```
Comment (clue4) [inline frontend/src/firebase/firebaseInteractor.ts]: got the ts error saying that this should be !==

Comment (clue4) [reply frontend/src/firebase/firebaseInteractor.ts]: got these compilation errors actually:

image

**Review by clue4 — CHANGES_REQUESTED** [review]
downloading all worked with some issues: missed some people (dev, diego, one of the lauras (maybe bc there were two lauras?), Meet, spam-test)
Downloading a single student worked -- altho lowkey... why are 188 network requests sent out when i click the download button for a single student.....

for durations in the durations file, is the duration in seconds? if so, can that be specified in the label like so: duration (in seconds)
image

is there no activity 1?  (screenshot from dillons, session 1)
+ assuming the incomplete/undefined means you just didn't finish session 1
image

+ on a similar vein, can change activity3image to activity3Part1image, same for activity3result, so that it matches the others? (honestly this is not as necessary, but if it's a simple fix might be helpful)
image

**Comment by dillydally414** [comment]
> downloading all worked with some issues: missed some people (dev, diego, one of the lauras (maybe bc there were two lauras?), Meet, spam-test)

Some people will get skipped if their data is invalid rather than tanking the whole download, did you see anything logged in the console?

> why are 188 network requests sent out when i click the download button for a single student.....

Uhhhh 😃 I will see if I can shrink this by making bulk calls instead of individual

> for durations in the durations file, is the duration in seconds? if so, can that be specified in the label like so: duration (in seconds)

yes it's in seconds, i was debating adding a label or not cause if they're gonna do anything with it programmatically adding a space might get funky, but i can ask this during the meeting

> is there no activity 1? (screenshot from dillons, session 1)

activities 1 and 4 have nothing interesting (user doesn't select anything) so we don't track any stats for them, same with the UI display for those activities

> assuming the incomplete/undefined means you just didn't finish session 1

yep, intervention happens before assessment (which is kinda backwards from how it's displayed but w/e)

> on a similar vein, can change activity3image to activity3Part1image, same for activity3result, so that it matches the others? (honestly this is not as necessary, but if it's a simple fix might be helpful)

tbh i'm kinda scared to make this change bc i'm not sure if it will mess up non-obvious stuff, plus it will also affect upload script. maybe we wait and do this after stuff is merged in so I can just do a find+replace all?

thank you for reviewing btw ❤️

**Comment by clue4** [comment]
@dillydally414 I did get "error: this word does not exist" four times in the console logs, which could explain maybe explain dev, diego, Meet, and spam-test? and perhaps laura isn't being caught because there's two of them? (maybe) and fun fact, the download all sent 1400+ network requests and I think all of them except one (the second one) were post requests? what are we posting when we're downloading info?

**Comment by dillydally414** [comment]
so theoretically i can reduce the number of network calls but i actually don't think it will reduce the number of reads to the database which is kinda annoying... since for these downloads we do have to access p much all the data. given that it would be somewhat of a large refactor to reduce the network calls with little actual payoff i might just leave as is (though i will investigate to see if i can parallelize better anywhere)

**Comment by dillydally414** [comment]
may need to discuss this with the clients though cause depending on how heavily this app is used there will be associated costs

**Review by clue4 — APPROVED** [review]
approving this specific pr as I see the eslint errors + network batching is being taken care of in the branch offshoot pr of this -- still need to review that one though. will try to get to it tomorrow 

also for my most recent test student on the new branch, I had ~31 network calls which is a good improvement! still need to verify if that has to do with # of assessments/data associated with student, but it looks promising
